declare -x OVPN_ADDITIONAL_CLIENT_CONFIG
declare -x OVPN_AUTH="SHA384"
declare -x OVPN_CIPHER="AES-256-GCM"
declare -x OVPN_CLIENT_TO_CLIENT
declare -x OVPN_CN="ovpn.abaranovskaya.com"
declare -x OVPN_COMP_LZO="0"
declare -x OVPN_DEFROUTE="1"
declare -x OVPN_DEVICE="tun"
declare -x OVPN_DISABLE_PUSH_BLOCK_DNS="1"
declare -x OVPN_DNS="1"
declare -x OVPN_ENV="/etc/openvpn/ovpn_env.sh"
declare -x OVPN_FRAGMENT
declare -x OVPN_MTU
declare -x OVPN_NAT="0"
declare -x OVPN_OTP_AUTH
declare -x OVPN_PORT="1194"
declare -x OVPN_PROTO="udp"
declare -x OVPN_PUSH
declare -x OVPN_ROUTES
declare -x OVPN_SERVER="192.168.255.0/24"
declare -x OVPN_SERVER_URL="udp://ovpn.abaranovskaya.com"
declare -x OVPN_TLS_CIPHER="TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384"
